apiVersion: v1
kind: ConfigMap
metadata:
  name: website-configmap
  namespace: website
  labels:
    projectName: website
data:
  MONGO_URI: mongodb://website-mongodb-svc:27017
  SERVER_URL: http://events-svc:5001
  PAYMEE_URL: https://sandbox.paymee.tn
  DB_NAME: Website
  COLLECTION_NAME_EVENT: EVENT
  COLLECTION_NAME_TRANSACTION: TRANSACTION
  COLLECTION_NAME_SUBS: SUBS