apiVersion: v1
kind: ConfigMap
metadata:
  name: website-configmap
  namespace: website
  labels:
    projectName: website
data:
  # URI to access mongodb internally / used in : server-go/variables
  MONGO_URI: mongodb://website-mongodb-svc:27017
  # To access website-server internally / used in : vue/api 
  SERVER_URL: http://website-server-svc:5000
  # Represents website-server external adress (needs to be updated later when creating ingress) / used in : server-go/variables
  SERVER_EXTERNAL_URL: http://localhost:5000
  # To interact with paymee APIs / used in: website, server-go/variables
  PAYMEE_URL: https://sandbox.paymee.tn
  # Mongo DB and collection names / used in server-go/variables
  DB_NAME: Website
  COLLECTION_NAME_EVENT: EVENT
  COLLECTION_NAME_TRANSACTION: TRANSACTION
  COLLECTION_NAME_SUBS: SUBS