kind: Secret
apiVersion: v1
metadata:
  name: website-secret
  namespace: website
  labels:
    projectName: website
    
data:
  # Paymee secret to verify payment status / used in: vue/api, server-go/variables
  PAYMEE_API_KEY: ""
  # Used to send e-mails / used in: vue/api
  # Can get at https://myaccount.google.com/apppasswords 
  SENDER_ADRESS: ""
  SENDER_PWD: ""
  # Paymee vendor Id to echange with a token / used in: vue/api
  VENDOR: ""
  # Credentials files to access google calendar service / used in: vue/api
  credentials.json: ""
  token.json: ""

type: Opaque