kind: Secret
apiVersion: v1
metadata:
  name: website-secret
  namespace: website
  labels:
    projectName: website
    
data:
  PAYMEE_API_KEY: ""
  SENDER_ADRESS: ""
  SENDER_PWD: ""
  VENDOR: ""
  credentials.json: ""
  token.json: ""

type: Opaque