apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-server-deploy
  namespace: website
  labels:
    projectName: website
spec:
  strategy: 
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: website-server
  replicas: 1
  template:
    metadata:
      labels:
        run: website-server
    spec:
      containers:
      - name: website-server
        image: creometry/website:serverV0.1.0
        ports:
        - containerPort: 5000
        env:
          - name: PAYMEE_URL
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: PAYMEE_URL 
          - name: PAYMEE_API_KEY
            valueFrom:
              secretKeyRef:
                name: website-secret
                key: PAYMEE_API_KEY 
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: MONGO_URI 
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: EVENTS_DB_NAME 
          - name: COLLECTION_NAME_EVENT
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: COLLECTION_NAME_EVENT 
          - name: COLLECTION_NAME_TRANSACTION
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: COLLECTION_NAME_TRANSACTION 
          - name: COLLECTION_NAME_SUBS
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: COLLECTION_NAME_SUBS 
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "5m"
            memory: "10Mi"  
        volumeMounts:
          - name: secret-volume
            mountPath: /app/credentials
      volumes:
      - name: secret-volume
        secret:
          secretName: website-secret
          items:
            - key: token.json
              path: token.json
            - key: credentials.json
              path: credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: website-server-svc
  namespace: website
  labels:
    projectName: website
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    run: website-server