apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-deploy
  namespace: website
  labels:
    projectName: website
spec:
  strategy: 
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: website-subscription
  replicas: 1
  template:
    metadata:
      labels:
        run: website-subscription
    spec:
      containers:
      - name: subscription
        image: azizbhy/website:subscription
        ports:
        - containerPort: 5000
        env:
          - name: SENDER_PWD
            valueFrom:
              secretKeyRef:
                name: website-secret
                key: SENDER_PWD 
          - name: SENDER_ADRESS
            valueFrom:
              secretKeyRef:
                name: website-secret
                key: SENDER_ADRESS 
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: MONGO_URI 
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: SUBS_DB_NAME 
          - name: COLLECTION_NAME
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: COLLECTION_NAME_SUBS 
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "5m"
            memory: "10Mi"    
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-svc
  namespace: website
  labels:
    projectName: website
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    run: website-subscription