name: Backend Service CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
      - 'v*'
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.0' # The Go version to download (if necessary) and use.
    
    # Install all the dependencies
    - name: Install dependencies
      working-directory: server-go
      run: |
        go version
        go mod tidy
        
    # Run build of the application
    - name: Run build
      working-directory: server-go
      run: go build . 
      
    # Run vet & lint on the code
    - name: Run vet & lint
      working-directory: server-go
      run: |
        go vet .
    
    # Run testing on the code
    # - name: Run testing
    #   working-directory: events
    #   run: cd test && go test -v
    
  deploy-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          creometry/website-server
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.WEBSITE_DOCKER_HUB }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: server-go
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}